server:
  port: 8887
  servlet:
    context-path: /auth-service
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tickets
    username: postgres
    password: postgres

  jackson:
    default-property-inclusion: non_absent

integrations:
  core-service:
    url: http://localhost:8888// #идет в core-service
    read-timeout: 10000
    write-timeout: 7000
    connect-timeout: 7000

