server:
  port: 8887
  servlet:
    context-path: /?????
spring:
  datasource:
    url: ???
    driver-class-name: ????
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: ???

integrations:
  core-service:
    url: http://localhost:8888// #идет в core-service
    read-timeout: 10000
    write-timeout: 7000
    connect-timeout: 7000

