server:
  port: 8887
  servlet:
    context-path: /?????
spring:
  datasource:
    url: ???
    driver-class-name: ????
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: ???

integrations:
  core-service:
    url: http://localhost:8889//
    read-timeout: 10000
    write-timeout: 7000
    connect-timeout: 7000

jwt:
  secret: ag%$45wqag$%asdf@4!q1F$qefw1asdfFFFEaFa23af4t5Gstdretfq2gsdfg$fafda
  lifetime: 36000000
