server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:2222"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8888
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1 # удалить core из url
            - PrefixPath=/tickets
            - JwtAuthFilter
        - id: setting-service
          uri: http://localhost:8899
          predicates:
            - Path=/settings/**
          filters:
            - StripPrefix=1
            - PrefixPath=/settings
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8887
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/auth-service
            - JwtAuthFilter

jwt:
  secretKey: ag%$45wqag$%asdf@4!q1F$qefw1asdfFFFEaFa23af4t5Gstdretfq2gsdfg$fafda
  lifeTimeToken: 36000000