server:
  port: 8181
  servlet:
    context-path: /user-service
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?options=--search_path%3Dticets
    username: postgres
    password: postgres


  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  jackson:
    default-property-inclusion: non_absent

