version: "3.9"
networks:
  default:
    name: 'myNet'
    external: true
services:
  postgres:
    image: postgres:13.3
    domainname: postgres
    environment:
      POSTGRES_DB: "tickets"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"