server:
  port: 8888
  servlet:
    context-path: /tickets
spring:
  datasource:
    url: ???
    driver-class-name: ???
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:

integrations:
  ???-service:
    url: http://localhost:8889/tickets-???/
    read-timeout: 10000
    write-timeout: 7000
    connect-timeout: 7000
