server:
  port: 8888
  servlet:
    context-path: /tickets
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tickets
    username: postgres
    password: postgres

  jackson:
    default-property-inclusion: non_absent

integrations:
  setting-service:
    url: http://localhost:8899/settings
    read-timeout: 10000
    write-timeout: 7000
    connect-timeout: 7000
  user-service:
    url: http://localhost:8181/user-service
    read-timeout: 10000
    write-timeout: 7000
    connect-timeout: 7000